version: '2'
services:
  nginx:
    depends_on:
      - web
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config_nginx/:/etc/nginx/conf.d/
    networks:
      backend:
        ipv4_address: 192.168.242.2

  web:
    build:
      context: .
      dockerfile: ./13.0/Dockerfile
    container_name: web
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      backend:
        ipv4_address: 192.168.242.3

  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      backend:
        ipv4_address: 192.168.242.4



volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.242.0/24
